### ISSUE TITLE
Git: Cloning problem with case non-sensitive filesystems

### ISSUE THREAD

**Issue by fredroy** [SofaDefrost/plugin.SofaPython3#104]
While cloning on a typical (sic) MacOS X partition:
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'bindings/Sofa/src/SofaPython3/Sofa/Core/Binding_Controller_doc.h'
  'bindings/Sofa/src/SofaPython3/Sofa/Core/binding_controller_doc.h'

and some updates in this file are not applied.
(By default APFS/HFS filesystems are case non-sensitive)
I guess it will be the case with Windows as well.

I don't know if there is a magic trick to fix this problem; I guess the nuclear option to modify the git history is a bit too invasive :)

**Comment by damienmarchal** [comment]
Hi Fred,

Thank for reporting. The worst is that I thing the the lowercase version is probably a mistake :(
